from __future__ import annotations

import math
import random

from gvns_smtwt_sdst import WTSDSInstance
from metaheuristic_common import (
    MetaheuristicResult,
    finish_result,
    initialize_search,
    random_insertion_neighbor,
    random_swap_neighbor,
)


def _estimate_initial_temperature(
    sequence: list[int],
    objective: int,
    control,
    rng: random.Random,
    samples: int = 30,
    target_acceptance: float = 0.80,
) -> float:
    """Estimate T0 so a typical uphill move is initially accepted often."""

    positive_deltas: list[int] = []

    for _ in range(samples):
        if control.exhausted():
            break
        candidate = random_swap_neighbor(sequence, rng)
        candidate_objective = control.evaluate(candidate)
        delta = candidate_objective - objective
        if delta > 0:
            positive_deltas.append(delta)

    if positive_deltas:
        mean_delta = sum(positive_deltas) / len(positive_deltas)
        return max(1e-12, -mean_delta / math.log(target_acceptance))

    # Fallback when sampled moves are all improving/equal.
    return max(1.0, 0.01 * max(objective, 1))


def solve_sa(
    instance: WTSDSInstance,
    *,
    time_limit: float | None = 10.0,
    max_evaluations: int | None = 20_000_000,
    seed: int | None = None,
    initial_temperature: float | None = None,
    cooling_rate: float = 0.95,
    steps_per_temperature: int | None = None,
    insertion_probability: float = 0.50,
    minimum_temperature: float = 1e-8,
) -> MetaheuristicResult:
    """Simulated Annealing for the SMTWT-SDST permutation problem.

    A candidate is generated by either a swap or an insertion move.
    Improving/equal moves are accepted; worsening moves are accepted with
    Metropolis probability exp(-delta / temperature).
    """

    if not 0.0 < cooling_rate < 1.0:
        raise ValueError("cooling_rate must be between 0 and 1.")
    if not 0.0 <= insertion_probability <= 1.0:
        raise ValueError("insertion_probability must be in [0, 1].")
    if initial_temperature is not None and initial_temperature <= 0:
        raise ValueError("initial_temperature must be positive.")
    if minimum_temperature <= 0:
        raise ValueError("minimum_temperature must be positive.")

    start, control, initial, initial_obj, _ = initialize_search(
        instance,
        time_limit=time_limit,
        max_evaluations=max_evaluations,
    )
    rng = random.Random(seed)

    current = list(initial)
    current_obj = initial_obj
    best = list(initial)
    best_obj = initial_obj

    if best_obj == 0 or instance.n_jobs < 2:
        return finish_result(
            "SA",
            start=start,
            control=control,
            best_sequence=best,
            best_objective=best_obj,
            initial_sequence=initial,
            initial_objective=initial_obj,
            iterations=0,
        )

    temperature = (
        float(initial_temperature)
        if initial_temperature is not None
        else _estimate_initial_temperature(current, current_obj, control, rng)
    )
    steps = steps_per_temperature or max(20, 10 * instance.n_jobs)
    if steps < 1:
        raise ValueError("steps_per_temperature must be at least 1.")

    iterations = 0

    while not control.exhausted() and temperature >= minimum_temperature:
        for _ in range(steps):
            if control.exhausted():
                break

            if rng.random() < insertion_probability:
                candidate = random_insertion_neighbor(current, rng)
            else:
                candidate = random_swap_neighbor(current, rng)

            candidate_obj = control.evaluate(candidate)
            delta = candidate_obj - current_obj

            if delta <= 0 or rng.random() < math.exp(-delta / temperature):
                current = candidate
                current_obj = candidate_obj

                if current_obj < best_obj:
                    best = list(current)
                    best_obj = current_obj
                    if best_obj == 0:
                        break

            iterations += 1

        if best_obj == 0:
            break
        temperature *= cooling_rate

    return finish_result(
        "SA",
        start=start,
        control=control,
        best_sequence=best,
        best_objective=best_obj,
        initial_sequence=initial,
        initial_objective=initial_obj,
        iterations=iterations,
    )
